### ISSUE TITLE
Nicely Done - TY - Sort Headers and call it a Day?

### ISSUE THREAD

**Issue by war59312** [Derekt2/CISA-Log4J-DB-Frontend#1]
Nice! Thank you.

Perhaps add the ability to sort headers and then call it a day.

Awesome sauce.

Edit: Perhaps also have the external links open in a new window if just clicked.

And add a link to https://derekt2.github.io/CISA-Log4J-DB-Frontend/ on the read me perhaps.

**Comment by Derekt2** [comment]
All great suggestions! Implemented them all.
